### ISSUE TITLE
setting headers in middleware doesn't work

### ISSUE THREAD

**Issue by carstenbaumhoegger** [apollostack/core-docs#220]
When trying to set headers via middleware as [documented](http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware)

```js
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    req.options.headers.authorization = localStorage.getItem('token') ? localStorage.getItem('token') : null;
    next();
  }
```

building the server fails with the error 

> Property 'authorization' does not exist on type 'HeadersInit'
> Unhandled PromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: [object Object]

I found a workaround to this by using
```js
createNetworkInterface({
  uri: '/graphql',
  opts: {
    headers: {
      authorization:  localStorage.getItem('token') ? localStorage.getItem('token') : null
    }
  }
})
```

Is this related to Apollo-Client release 0.5?

**Comment by stubailo** [comment]
The second code snippet doesn't do what you want - it only sets the header once when the network interface is created, so if the user logs out it won't be updated.

I'm confused about the first error, are you using some kind of runtime type checking or typescript or similar?

**Comment by carstenbaumhoegger** [comment]
sorry for the late response.

yes, the second snippet doesn't work as I first expected, but I got the first snippet working with TypeScript, it was way simpler than I thought. I simply replaced

```js
    req.options.headers.authorization = localStorage.getItem('token') ? localStorage.getItem('token') : null;
```
with
```js
    req.options.headers['authorization']= localStorage.getItem('token') ? localStorage.getItem('token') : null;
```

The snippet as specified in the docs doesn't work with mit TypeScript 2.0.6 setup.

**Comment by stubailo** [comment]
The snippets in the docs are not written for TypeScript, only for regular JavaScript. So this is to be expected. If you send a PR to change the snippet though I'll accept it because the second one will work with JS and TS.
